# Import and load data

In [1]:
import pandas as pd

In [6]:
df = pd.read_csv('Customer marketing.csv', sep='\t')
df.head()

,ID_,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
0,5524,1957,Graduation,Single,58138.0,0,0,04-09-2012,58,635,...,7,0,0,0,0,0,0,3,11,1
1,2174,1954,Graduation,Single,46344.0,1,1,08-03-2014,38,11,...,5,0,0,0,0,0,0,3,11,0
2,4141,1965,Graduation,Together,71613.0,0,0,21-08-2013,26,426,...,4,0,0,0,0,0,0,3,11,0
3,6182,1984,Graduation,Together,26646.0,1,0,10-02-2014,26,11,...,6,0,0,0,0,0,0,3,11,0
4,5324,1981,PhD,Married,58293.0,1,0,19-01-2014,94,173,...,5,0,0,0,0,0,0,3,11,0

In [8]:
df.shape

(2240, 29)

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2240 entries, 0 to 2239
Data columns (total 29 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID_                  2240 non-null   int64
 1   Year_Birth           2240 non-null   int64
 2   Education            2240 non-null   str
 3   Marital_Status       2240 non-null   str
 4   Income               2216 non-null   float64
 5   Kidhome              2240 non-null   int64
 6   Teenhome             2240 non-null   int64
 7   Dt_Customer          2240 non-null   str
 8   Recency              2240 non-null   int64
 9   MntWines             2240 non-null   int64
 10  MntFruits            2240 non-null   int64
 11  MntMeatProducts      2240 non-null   int64
 12  MntFishProducts      2240 non-null   int64
 13  MntSweetProducts     2240 non-null   int64
 14  MntGoldProds         2240 non-null   int64
 15  NumDealsPurchases    2240 non-null   int64
 16  NumWebPurchases      2240 non-null   int64
 17  NumCatalogPurchases  2240 non-null   int64
 18  NumStorePurchases    2240 non-null   int64
 19  NumWebVisitsMonth    2240 non-null   int64
 20  AcceptedCmp3         2240 non-null   int64
 21  AcceptedCmp4         2240 non-null   int64
 22  AcceptedCmp5         2240 non-null   int64
 23  AcceptedCmp1         2240 non-null   int64
 24  AcceptedCmp2         2240 non-null   int64
 25  Complain             2240 non-null   int64
 26  Z_CostContact        2240 non-null   int64
 27  Z_Revenue            2240 non-null   int64
 28  Response             2240 non-null   int64
dtypes: float64(1), int64(25), str(3)
memory usage: 507.6 KB

# Rename columns to lower case

In [12]:
#rename columns to lower case and uniform format
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')
df.columns

Index(['id_', 'year_birth', 'education', 'marital_status', 'income', 'kidhome',
       'teenhome', 'dt_customer', 'recency', 'mntwines', 'mntfruits',
       'mntmeatproducts', 'mntfishproducts', 'mntsweetproducts',
       'mntgoldprods', 'numdealspurchases', 'numwebpurchases',
       'numcatalogpurchases', 'numstorepurchases', 'numwebvisitsmonth',
       'acceptedcmp3', 'acceptedcmp4', 'acceptedcmp5', 'acceptedcmp1',
       'acceptedcmp2', 'complain', 'z_costcontact', 'z_revenue', 'response'],
      dtype='str')

# Missing Value handling

In [ ]:
#Missing values
df.isnull().sum()

id_                     0
year_birth              0
education               0
marital_status          0
income                 24
kidhome                 0
teenhome                0
dt_customer             0
recency                 0
mntwines                0
mntfruits               0
mntmeatproducts         0
mntfishproducts         0
mntsweetproducts        0
mntgoldprods            0
numdealspurchases       0
numwebpurchases         0
numcatalogpurchases     0
numstorepurchases       0
numwebvisitsmonth       0
acceptedcmp3            0
acceptedcmp4            0
acceptedcmp5            0
acceptedcmp1            0
acceptedcmp2            0
complain                0
z_costcontact           0
z_revenue               0
response                0
dtype: int64

In [16]:
# Handle missing values (Only income column has missing values)
df['income'] = df['income'].fillna(df['income'].median())
df['income'].isnull().sum()

np.int64(0)

In [17]:
df.isnull().sum()

id_                    0
year_birth             0
education              0
marital_status         0
income                 0
kidhome                0
teenhome               0
dt_customer            0
recency                0
mntwines               0
mntfruits              0
mntmeatproducts        0
mntfishproducts        0
mntsweetproducts       0
mntgoldprods           0
numdealspurchases      0
numwebpurchases        0
numcatalogpurchases    0
numstorepurchases      0
numwebvisitsmonth      0
acceptedcmp3           0
acceptedcmp4           0
acceptedcmp5           0
acceptedcmp1           0
acceptedcmp2           0
complain               0
z_costcontact          0
z_revenue              0
response               0
dtype: int64

# Remove Duplicate rows

In [20]:
# check duplicate values and remove duplicate rows
print("Duplicate values: ", df.duplicated().sum())
df.drop_duplicates(inplace=True)

Duplicate values:  0

In [21]:
print("Duplicate values after removal: ", df.duplicated().sum())

Duplicate values after removal:  0

# Standardized the categorical data columns

In [27]:
df['education'].value_counts()

education
Graduation    1127
PhD            486
Master         370
2n Cycle       203
Basic           54
Name: count, dtype: int64

In [28]:
df['education'].unique()

<StringArray>
['Graduation', 'PhD', 'Master', 'Basic', '2n Cycle']
Length: 5, dtype: str

Standardize the education column values

In [ ]:
# standardize the education column values
education_mapping = {
    'Graduation': 'Graduate', 
    'PhD': 'Postgraduate', 
    'Master': 'Postgraduate', 
    'Basic': 'Undergraduate', 
    '2n Cycle': 'Undergraduate'
}
df['education'] = df['education'].map(education_mapping)

In [33]:
print(df['education'].unique())
print(df['education'].value_counts())

<StringArray>
['Graduate', 'Postgraduate', 'Undergraduate']
Length: 3, dtype: str
education
Graduate         1127
Postgraduate      856
Undergraduate     257
Name: count, dtype: int64

Standardize the Marital status column values

In [35]:
print(df['marital_status'].unique())
print(df['marital_status'].value_counts())

<StringArray>
['Single', 'Together', 'Married', 'Divorced', 'Widow', 'Alone', 'Absurd',
 'YOLO']
Length: 8, dtype: str
marital_status
Married     864
Together    580
Single      480
Divorced    232
Widow        77
Alone         3
Absurd        2
YOLO          2
Name: count, dtype: int64

In [36]:
# standardize the Marital_status column values
marital_status_mapping = {
    'Single': 'Single', 
    'Together': 'Partnered', 
    'Married': 'Married', 
    'Divorced': 'Divorced', 
    'Widow': 'Widowed', 
    'Alone': 'Single', 
    'Absurd': 'Single',
    'YOLO': 'Single'
}
df['marital_status'] = df['marital_status'].map(marital_status_mapping)

In [37]:
print(df['marital_status'].unique())
print(df['marital_status'].value_counts())

<StringArray>
['Single', 'Partnered', 'Married', 'Divorced', 'Widowed']
Length: 5, dtype: str
marital_status
Married      864
Partnered    580
Single       487
Divorced     232
Widowed       77
Name: count, dtype: int64

# Convert Date Formats & Fix Data Types

In [41]:
df['dt_customer']

0       04-09-2012
1       08-03-2014
2       21-08-2013
3       10-02-2014
4       19-01-2014
           ...
2235    13-06-2013
2236    10-06-2014
2237    25-01-2014
2238    24-01-2014
2239    15-10-2012
Name: dt_customer, Length: 2240, dtype: str

In [42]:
# Convert Date Formats & Fix Data Types
df['dt_customer'] = pd.to_datetime(df['dt_customer'], format='mixed')

In [44]:
df

,id_,year_birth,education,marital_status,income,kidhome,teenhome,dt_customer,recency,mntwines,...,numwebvisitsmonth,acceptedcmp3,acceptedcmp4,acceptedcmp5,acceptedcmp1,acceptedcmp2,complain,z_costcontact,z_revenue,response
0,5524,1957,Graduate,Single,58138.0,0,0,2012-04-09,58,635,...,7,0,0,0,0,0,0,3,11,1
1,2174,1954,Graduate,Single,46344.0,1,1,2014-08-03,38,11,...,5,0,0,0,0,0,0,3,11,0
2,4141,1965,Graduate,Partnered,71613.0,0,0,2013-08-21,26,426,...,4,0,0,0,0,0,0,3,11,0
3,6182,1984,Graduate,Partnered,26646.0,1,0,2014-10-02,26,11,...,6,0,0,0,0,0,0,3,11,0
4,5324,1981,Postgraduate,Married,58293.0,1,0,2014-01-19,94,173,...,5,0,0,0,0,0,0,3,11,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2235,10870,1967,Graduate,Married,61223.0,0,1,2013-06-13,46,709,...,5,0,0,0,0,0,0,3,11,0
2236,4001,1946,Postgraduate,Partnered,64014.0,2,1,2014-10-06,56,406,...,7,0,0,0,1,0,0,3,11,0
2237,7270,1981,Graduate,Divorced,56981.0,0,0,2014-01-25,91,908,...,6,0,1,0,0,0,0,3,11,0
2238,8235,1956,Postgraduate,Partnered,69245.0,0,1,2014-01-24,8,428,...,3,0,0,0,0,0,0,3,11,0
2239,9405,1954,Postgraduate,Married,52869.0,1,1,2012-10-15,40,84,...,7,0,0,0,0,0,0,3,11,1

# Export the Cleaned Dataset

In [45]:
df.to_csv("cleaned_customer_personality.csv", index=False)
print("Data cleaning complete! Cleaned dataset exported successfully.")

Data cleaning complete! Cleaned dataset exported successfully.